language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.8
script:
- sbt clean
- sbt coverage test
- sbt coverageReport
- sbt coverageAggregate
after_success:
- export CODACY_PROJECT_TOKEN=a23ff03e0ab24a318112691145ac0b0c
- sbt codacyCoverage
- sbt scalastyle